<a href="https://colab.research.google.com/github/EmmanueleVilla/quantum_computing/blob/main/Colab_06a_Protocollo_BB84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
alice_qubits = np.random.randint(0, 2, 10000)
alice_qubits

array([1, 1, 0, ..., 0, 0, 1])

In [ ]:
alice_basis = np.random.randint(0, 2, 10000)
alice_basis

array([0, 0, 1, ..., 1, 0, 0])

In [ ]:
bob_basis = np.random.randint(0, 2, 10000)
bob_basis

array([1, 0, 0, ..., 1, 0, 1])

In [ ]:
bob_measurements = [alice_qubits[i] if alice_basis[i] == bob_basis[i] else np.random.randint(0, 2) for i in range(10000)]
bob_measurements = np.asarray(bob_measurements)
bob_measurements

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
pairs = zip(alice_qubits, bob_measurements)
pairs

In [ ]:
correct = sum(1 for alice, bob in pairs if alice==bob)
print(correct/100)

74.86


In [ ]:
eve_basis = np.random.randint(0, 2, 10000)
eve_basis

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
bob_measurements = [alice_qubits[i] if alice_basis[i] == bob_basis[i] and eve_basis[i] == bob_basis[i] else np.random.randint(0, 2) for i in range(10000)]
bob_measurements = np.asarray(bob_measurements)
bob_measurements

array([1, 1, 1, ..., 1, 0, 0])

In [ ]:
pairs = zip(alice_qubits, bob_measurements)
pairs

In [ ]:
correct = sum(1 for alice, bob in pairs if alice==bob)
print(correct/100)

62.67
